### ISSUE TITLE
請教專案執行問題

### ISSUE THREAD

**Issue by blantt** [isdaniel/ElectronicInvoice_TW#3]
您好!
  請教我下載專案後測試,執行時,
  這段代碼出現error: public class MyApi : ApiBase<MyQryWinningListModel>
錯誤訊息為
錯誤	CS7036	未提供任何可對應到 'ApiBase<MyQryWinningListModel>.ApiBase(IConfig, ISysLog)' 之必要型式參數 'config' 的引數 

請教是何原因呢 ? 謝謝

**Comment by isdaniel** [comment]
如果你要擴充使用ApiBase需要指定泛型,目前Base Class需要傳入 `(IConfig config,ISysLog log)` 物件當作建構子參數 ![](https://i.imgur.com/xw0H1QC.png)

**Comment by isdaniel** [comment]
或是能否提供程式碼借我看一下

**Comment by blantt** [comment]
> 或是能否提供程式碼借我看一下

你好,可是我是下載此專案,什麼都沒有改時,就出現這錯誤耶?
\ElectronicInvoice_TW-master\ElectronicInvoice_TW-master\Demo\EInvoiceDemo\EInvoiceDemo\Program.cs
裡面, public class MyApi : ApiBase<MyQryWinningListModel> 這裡出現此錯誤!

thks

**Comment by isdaniel** [comment]
了解 請問你是下載Nuget哪個版本? 

目前最新是[1.1.0.4 ](https://www.nuget.org/packages/ElectronicInvoice_TW/1.1.0.4 )

**Comment by blantt** [comment]
> 了解 請問你是下載Nuget哪個版本?
> 
> 目前最新是[1.1.0.4 ](https://www.nuget.org/packages/ElectronicInvoice_TW/1.1.0.4)
我不是用nuget下載耶,我是直接從github download zip檔回來run
參考圖片:
https://drive.google.com/file/d/11kTqvR5UljGqk1Cp6wjgOTsvyM4fMCVS/view?usp=sharing

不好意思,我對github沒那麼熟,如有不正確請再和我說!

**Comment by isdaniel** [comment]
如果你是一般專案,我會建議使用nuget來安裝
https://docs.microsoft.com/zh-tw/nuget/quickstart/install-and-use-a-package-in-visual-studio

你看起來是想要繼承ApiBase<>建立自己Invoice類別產品

因為ApiBase是泛型父類別.所以你需要給一個類別

這裡有一個Sample Code給你參考

```sql
    public class MyApi : ApiBase<YouModel>
    {
        public MyApi(IConfig config, ISysLog log) : base(config, log)
        {
        }

        protected override string SetParameter(YouModel model)
        {
            //implement your parameter.
            return string.Empty;
        }
    }

    public class YouModel
    {
        //your parameter model
    }
```

這是我之前詳細解說我這個框架的細節文章給你參考一下 https://dotblogs.com.tw/daniel/2017/10/15/203221

**Comment by blantt** [comment]
謝謝您詳細的回答~ 調整程式碼後可以執行了~
我目前在研究電子發票的API,您的專案對我很幫助 ~ 謝謝!
